#!/bin/bash

#PBS -N plasma
#PBS -l walltime=07:00:00
#PBS -l nodes=1:ppn=64
#PBS -q blade

cd $PBS_O_WORKDIR

module load intel/13.0
module load mkl/intel
module load plasma/2.8.0/intel/mkl

SIZE=20000

for TH in 16 24 32 48 64 #1 2 4 8 16 24 32 48 64
do

# NDIM=$((4000+1000*$S))
export PLASMA_NUM_THREADS=$TH

count=1

while [ $count -le 6 ]
do

./test_plasma.x $SIZE $PLASMA_NUM_THREADS
count=$((count+1))

done

done
