#!/bin/bash

#PBS -N scalapack
#PBS -l walltime=00:01:00
#PBS -l nodes=1:ppn=20

cd $PBS_O_WORKDIR

module load testing
module load mkl/15.0
module load openmpi/1.10.1/intel/15.0 #impi-trial/5.0.1.035

mpirun -np 20 pdsyev.x 400 4 5 10
