#!/bin/bash

#PBS -N scalapack
#PBS -l walltime=05:20:00
#PBS -l nodes=1:ppn=20
#PBS -q reserved3

cd $PBS_O_WORKDIR

module load testing
module load mkl/15.0 #intel
module load openmpi #/1.10.1/intel/15.0 #impi-trial/5.0.1.035

# mpirun -np 20 pdsyev.x 200 4 5 10

for S in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 # 15 16
do

NDIM=$((4000+1000*$S))
# echo $NDIM
count=1
while [ $count -le 10 ]
do
mpirun -np 20 pdsyev.x $NDIM 10 2 64
# mpirun -np 20 pdsyev.x $NDIM 4 5 64
# mpirun -np 20 1x20pdsyev.x $NDIM 1 20 64
count=$((count+1))
done
done
