#!/bin/bash

#PBS -N magma
#PBS -l walltime=02:00:00
#PBS -l nodes=1:ppn=20:gpu
#PBS -q gpu

cd $PBS_O_WORKDIR

module load intel/14.0
module load mkl/11.1
module load cudatoolkit/6.5
module load magma/1.6.1/intel/14.0/mkl/11.1/cudatoolkit/6.5

for SIZE in 4000 6000 8000 10000 12000 14000 16000 18000
do

count=1

while [ $count -le 6 ]
do

    ./magma_dsyevd.x $SIZE
    count=$((count+1))

done

done
